companies = [
    {
        "company_name": "OpenAI",
        "short_description": "OpenAI creates artificial intelligence technologies to assist with tasks and provide support for human activities.",
        "location_identifiers": "San Francisco, California, United States, North America",
        "website_url": "https://www.openai.com",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/jjykwqqhsscreywea4gb",
        "api_identifier": "cf2c678c-b81a-80c3-10d1-9c5e76448e51",
        "founded_year": "2015",
        "ai_prompt": "OpenAI anticipates significant growth in both the near and long term as demand for artificial intelligence technologies escalates across various sectors. With advancements in natural language processing and machine learning, OpenAI is poised to enhance its offerings to businesses and consumers alike. Recent data suggests the AI market may reach $1 trillion by 2030, emphasizing OpenAI's strategic position. The company's flagship product, ChatGPT, caters to a diverse clientele, from tech firms to educational institutions. While share prices remain speculative due to its private status, estimates suggest a potential valuation range of $80 billion to $100 billion, reflecting strong investor confidence in the future of AI.",
        "categories": "Technology",
        "num_employees_enum": "501-1000",
        "revenue_range": "$1B - $5B",
        "investors": "Microsoft, LinkedIn, Reid Hoffman, Peter Thiel, Khosla Ventures",
    },
    {
        "company_name": "Anthropic",
        "short_description": "Anthropic is an AI safety and research company that focuses on increasing the safety of large-scale AI systems.",
        "location_identifiers": "San Francisco, California, United States, North America",
        "website_url": "https://www.anthropic.com",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/02bb58922b3d4d64b082982f275896c8",
        "api_identifier": "e10aaff2-4d89-46d4-820b-b4f64b8d42ca",
        "founded_year": "2020",
        "ai_prompt": "Anthropic, an AI safety and research company, is poised for robust business development in both the near and long term as interest in safe and responsible AI systems surges. With the rapid advancement of generative AI technologies and heightened regulatory scrutiny, organizations will increasingly seek guidance on AI safety. Anthropic’s core product, Claude—a state-of-the-art conversational AI model—appeals to businesses across sectors keen on implementing AI responsibly. As demand grows, analysts speculate that with strong positioning in the market, Anthropic's share price could range from $30 to $50 in the coming years, depending on overall market conditions and successful product adoption.",
        "categories": "Technology",
        "num_employees_enum": "101-500",
        "revenue_range": "$10M - $50M",
        "investors": "Google, Sam Bankman-Fried, Chris Clark, Eric Schmidt, Jason Horowitz, Reid Hoffman, and others.",
    },
    {
        "company_name": "xAI",
        "short_description": "XAI is an AI company that develops a platform to accelerate human scientific discovery.",
        "location_identifiers": "Burlingame, California, United States, North America",
        "website_url": "https://x.ai",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/fx3dkdpnolvubjldo54x",
        "api_identifier": "fb1e8b91-ca1f-46fa-b773-b147af49088c",
        "founded_year": "2023",
        "ai_prompt": "xAI is poised for significant growth in both the near and long term, driven by its innovative platform designed to accelerate human scientific discovery. By leveraging cutting-edge artificial intelligence technologies, xAI aims to streamline research processes across various sectors, enhancing collaboration among scientists and researchers. In the near term, the company is expected to attract attention from academic institutions and biotech firms seeking to boost their research efficiency. Long-term prospects appear promising as more industries recognize the value of AI in scientific advancement. Currently, xAI’s main product offers a robust platform that serves researchers and institutions dedicated to groundbreaking discoveries. With an anticipated share price range of $25 to $35 in the upcoming quarters, the company is well-positioned to become a leader in the intersection of AI and scientific exploration.",
        "categories": "Technology",
        "num_employees_enum": "101-500",
        "revenue_range": "$1M - $5M",
        "investors": "Elon Musk, Sam Altman, Greg Brockman, Ilya Sutskever, Jared Cohen",
    },
    {
        "company_name": "Perplexity",
        "short_description": "Perplexity is an AI-chat-based conversational search engine that delivers answers to questions using language models.",
        "location_identifiers": "San Francisco, California, United States, North America",
        "website_url": "https://www.perplexity.ai",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/ae1234e9e4bb4347b589eceb981c2a8a",
        "api_identifier": "5639c94c-408b-450a-9694-df238f6d9da9",
        "founded_year": "2022",
        "ai_prompt": "Perplexity, the innovative AI-chat-based conversational search engine, is poised for substantial growth in both the near- and long-term. In the immediate future, the demand for intuitive search solutions powered by advanced language models is on the rise, suggesting a promising trajectory for user engagement and retention. Over the long haul, as AI technology continues to evolve, Perplexity could solidify its position as a leader in conversational search. The platform primarily caters to individuals seeking quick and precise information across various domains. Based on industry trends, the expected share price range could hover between $20 and $30, reflecting its potential in a rapidly expanding market.",
        "categories": "Technology",
        "num_employees_enum": "11-50",
        "revenue_range": "$1M - $5M",
        "investors": "Accel, Coatue Management, Tiger Global Management, and individual angel investors",
    },
    {
        "company_name": "TPG",
        "short_description": "TPG is a private investment firm that manages capital across a series of funds.",
        "location_identifiers": "San Francisco, California, United States, North America",
        "website_url": "http://www.tpg.com",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/m4kqlztzzkvnlwozagur",
        "api_identifier": "7a2512ce-16cb-75ac-2f6b-84ff53b41d03",
        "founded_year": "1992",
        "ai_prompt": "TPG, a prominent private investment firm, is poised for steady near-term and long-term growth, leveraging its extensive experience across diversified sectors. With over $100 billion in assets under management, TPG has demonstrated resilience amid economic fluctuations, continually attracting institutional investors. The firm focuses on technology, healthcare, and consumer sectors, catering to a wide range of clients from startups to mature corporations. While TPG is not publicly traded, recent valuations suggest strong performance, reflecting its robust investment strategy.",
        "categories": "Finance",
        "num_employees_enum": "101-500",
        "revenue_range": "$1B - $5B",
        "investors": "TPG Capital, TPG Growth, TPG Real Estate Partners, The Sixth Street Partners, TPG Pace Holdings, TPG's Investment Team.",
    },
    {
        "company_name": "Bluesky",
        "short_description": "Bluesky is a social media platform fostering open connections and creativity.",
        "location_identifiers": "Seattle, Washington, United States, North America",
        "website_url": "https://blueskyweb.xyz",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/94c5758af6c74a64a1c4897299be8a1c",
        "api_identifier": "bd2db13f-b6fe-438d-97fd-9ba3a833514d",
        "founded_year": "2022",
        "ai_prompt": "Bluesky, as a burgeoning social media platform, is poised for significant growth in both the near and long term. Initially focusing on fostering open connections and creativity among users, I expect Bluesky to capitalize on the rising demand for decentralized social media experiences. In the long run, it may attract a diverse user base, particularly among younger demographics disenchanted with traditional platforms. Its unique approach could lead to increased user engagement and potential monetization through advertising. Currently, Bluesky primarily targets creators and users seeking authentic interactions. While specific share price predictions remain speculative, market analysts suggest it could range between $20 and $30, reflective of its innovative position in the social media landscape.",
        "categories": "Technology",
        "num_employees_enum": "51-100",
        "revenue_range": "$1M - $5M",
        "investors": "Twitter, Alwaleed Philanthropies, Capital Group, Andreessen Horowitz, Betaworks, Union Square Ventures",
    },
    {
        "company_name": "Polymarket",
        "short_description": "Polymarket is a prediction market platform where traders predict future event outcomes, reacting to news in real time.",
        "location_identifiers": "New York, New York, United States, North America",
        "website_url": "https://polymarket.com",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/radxv99bd8jwiuqwxt95",
        "api_identifier": "f819088f-5273-4d13-9175-8896e772d25b",
        "founded_year": "2018",
        "ai_prompt": "Polymarket, a pioneering prediction market platform, is poised for significant near-term growth as interest in decentralized finance (DeFi) expands. With a unique model allowing users to trade on the outcomes of future events, it capitalizes on real-time news and trends. In the long term, Polymarket could see increased institutional adoption, especially as regulatory frameworks evolve. They cater to individual traders, research analysts, and enthusiasts interested in market sentiment. Given the volatility of the crypto sector, expected share price could range between $10 and $20, depending on market conditions and operational enhancements.",
        "categories": "Technology",
        "num_employees_enum": "51-100",
        "revenue_range": "$1M - $5M",
        "investors": "Coatue Management, Digital Currency Group, Pantera Capital, Arrington XRP Capital, Compound VC, Consensus Lab, Tachyon, 0x Labs",
    },
    {
        "company_name": "Cyera",
        "short_description": "Cyera is an AI-powered data security platform that gives enterprises deep context on their data to assure cyber-resilience and compliance.",
        "location_identifiers": "New York, New York, United States, North America",
        "website_url": "https://cyera.io",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/786c92de08504bee9299a4ab67508648",
        "api_identifier": "8cb324b0-7f3e-4b08-8814-f26ffe2480d8",
        "founded_year": "2021",
        "ai_prompt": "Cyera is poised for significant growth in both the near and long term as enterprises increasingly prioritize data security and compliance amidst rising cyber threats. With the market for data security projected to reach over $200 billion by 2025, Cyera's AI-powered platform, which provides deep contextual insights into data usage and vulnerabilities, positions it well for expansion. Its main offerings cater to industries with stringent compliance requirements, such as finance and healthcare, serving clients like major banks and healthcare organizations. As Cyera continues to innovate and scale, analysts expect its share price to range between $15 and $25, reflecting strong confidence in its business model and growth trajectory.",
        "categories": "Technology",
        "num_employees_enum": "51-100",
        "revenue_range": "$1M - $5M",
        "investors": "Costanoa Ventures, Greylock Partners, Bessemer Venture Partners, 1Sharpe Capital",
    },
    {
        "company_name": "Neuralink",
        "short_description": "Neuralink develops a brain machine interface that provides solutions for those with paralysis.",
        "location_identifiers": "Fremont, California, United States, North America",
        "website_url": "https://www.neuralink.com",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/yxdzggbjk9yxhl2g2t1s",
        "api_identifier": "46ace8da-8b4f-e267-757c-158bae1c8c66",
        "founded_year": "2016",
        "ai_prompt": "Neuralink's near-term prospects appear promising as they work towards regulatory approval for their brain-machine interface technology, aimed at revolutionizing treatment for paralysis and neurological disorders. In the long term, the potential market could expand significantly, targeting applications in cognitive enhancement and neuroprosthetics. With a current speculative valuation in the range of $5 to $10 billion, the expected share price, upon future IPO, may fall between $20 to $40, depending on market conditions. The company's primary product is an innovative implantable device designed to interpret and stimulate brain activity, targeting both healthcare providers and individuals with paralysis.",
        "categories": "Healthcare",
        "num_employees_enum": "101-500",
        "revenue_range": "$10M - $50M",
        "investors": "Elon Musk, DFJ Growth, Founders Fund, Gigafund, and others.",
    },
    {
        "company_name": "BlackRock",
        "short_description": "BlackRock is an investment company that offers its services to institutions, intermediaries, foundations, and individual investors.",
        "location_identifiers": "New York, New York, United States, North America",
        "website_url": "http://www.blackrock.com",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/mrkgh4aeunkd2au7zaxf",
        "api_identifier": "931f7202-91fd-ab26-c07d-06518289ef06",
        "founded_year": "1988",
        "ai_prompt": "In the near term, BlackRock is expected to continue expanding its investment management services, leveraging its expertise in ETFs and sustainable investing. Long-term growth may be driven by increasing demand for responsible investment solutions and technology-driven portfolio management. As of 2023, BlackRock manages over $9 trillion in assets, positioning itself as a leader in the industry. Its primary products include mutual funds, ETFs, and alternative investments, catering to diverse clients such as institutions, intermediaries, and individual investors. Analysts predict BlackRock's share price may range between $600 to $700, reflecting its robust market position and potential for sustained growth.",
        "categories": "Finance",
        "num_employees_enum": "10001-50000",
        "revenue_range": "$100B - $500B",
        "investors": "BlackRock, institutional investors, high-net-worth individuals, pension funds, endowments, sovereign wealth funds, insurance companies, family offices.",
    },
    {
        "company_name": "Rocket Lab",
        "short_description": "Rocket Lab is an aerospace company that specializes in satellite, rocket, and spacecraft design, construction, and launch operations.",
        "location_identifiers": "Long Beach, California, United States, North America",
        "website_url": "https://www.rocketlabusa.com",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/cktwncwewldvaqjfbtgu",
        "api_identifier": "5794d0e0-27f6-1c8f-181d-0cd2d1ec84de",
        "founded_year": "2006",
        "ai_prompt": "Rocket Lab is poised for significant growth in both the near and long term, driven by increasing demand for small satellite launches and expanding partnerships with commercial and government clients. In the near term, their Electron rocket continues to perform well, facilitating frequent launches, while the Photon satellite platform is gaining traction. Looking ahead, Rocket Lab's collaboration with NASA and other space agencies may enhance their market position. The company aims to offer comprehensive solutions from launch to satellite deployment, primarily targeting clients in telecommunications, Earth observation, and science. Based on current market trends, analysts project the share price to range between $10 and $15 in the coming months, reflecting confidence in their innovative offerings and operational efficiency.",
        "categories": "Aerospace & Defense",
        "num_employees_enum": "101-500",
        "revenue_range": "$100M - $500M",
        "investors": "Vector Capital, Neutron Holdings, New Zealand government, Lockheed Martin, Bessemer Venture Partners",
    },
    {
        "company_name": "SoundHound",
        "short_description": "SoundHound is a voice AI platform that enables businesses to provide conversational experiences to their customers.",
        "location_identifiers": "Santa Clara, California, United States, North America",
        "website_url": "http://www.soundhound.com",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/xf9s6rqp4sztd1qepgak",
        "api_identifier": "979544f7-6a87-8579-306a-ea03a05a3071",
        "founded_year": "2005",
        "ai_prompt": "In the near term, SoundHound is poised to capitalize on the growing demand for voice AI technologies, with businesses increasingly seeking conversational experiences for customer engagement. By leveraging its innovative platform, the company aims to expand its market share in sectors like automotive, consumer electronics, and telecommunications. Long-term, as AI integration becomes standard, SoundHound could see significant growth in revenues and partnerships. Their flagship product, the SoundHound Voice AI, serves various clients, including major automotive brands. Analysts project a share price range of $15 to $25 as demand surges.",
        "categories": "Technology",
        "num_employees_enum": "101-500",
        "revenue_range": "$10M - $50M",
        "investors": "SoundHound Inc. has received investment from the following investors: A.Capital Ventures, GGV Capital, Qualcomm Ventures, Scribble Ventures, and Samsung.",
    },
    {
        "company_name": "LambdaTest",
        "short_description": "LambdaTest provides cloud-based tools for cross-browser testing of web applications on various browsers and operating systems.",
        "location_identifiers": "San Francisco, California, United States, North America",
        "website_url": "https://www.lambdatest.com",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/2ae5c3380413447b8255ac841c227cb0",
        "api_identifier": "1956b5a4-5fc5-8c76-580a-63190ebf77b9",
        "founded_year": "2017",
        "ai_prompt": "LambdaTest is poised for significant growth both in the near and long term, driven by the increasing emphasis on quality assurance in web development and the trend towards remote work. As more businesses embrace digital transformation, the demand for cross-browser testing tools is likely to rise. Currently, their cloud-based platform serves a diverse clientele, including companies like Microsoft and IBM, who rely on LambdaTest to ensure their applications function seamlessly across different browsers and operating systems. With robust integration capabilities and an expanding feature set, LambdaTest could see its valuation rise, potentially placing its share price in the range of $15 to $25, should it pursue a public offering.",
        "categories": "Technology",
        "num_employees_enum": "101-500",
        "revenue_range": "$10M - $50M",
        "investors": "Accel, Chromo Invest, 500 Startups, UpWest Labs, Afore Capital",
    },
    {
        "company_name": "International Finance Corporation",
        "short_description": "International Finance Corporation is a private equity and venture capital subsidiary focused on the private sector in developing countries.",
        "location_identifiers": "Washington, District of Columbia, United States, North America",
        "website_url": "http://www.ifc.org",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/08353513133f465092ba6180efd5f897",
        "api_identifier": "3afb8ef5-2b6c-7788-7b38-53ecbb89d72e",
        "founded_year": "1956",
        "ai_prompt": "The International Finance Corporation (IFC), as a leading private equity and venture capital subsidiary of the World Bank, is well-positioned for growth in both the near and long term. With a focus on investing in sustainable projects in developing nations, IFC aims to address critical challenges in infrastructure, health, and agriculture, expecting to contribute significantly to economic resilience and job creation. In the near term, IFC will likely expand its investments in green technologies, responding to the global push for climate-friendly initiatives. Their main products revolve around equity investments and advisory services to private sector clients, primarily targeting small and medium enterprises in emerging markets. Given its strategic focus, analysts expect its share price to stabilize in the $60-$75 range, reflecting steady growth driven by successful project investments.",
        "categories": "Financial Services",
        "num_employees_enum": "10001-50000",
        "revenue_range": "$1B - $5B",
        "investors": "World Bank Group, member countries, private investors, development finance institutions.",
    },
    {
        "company_name": "Techstars",
        "short_description": "Techstars is an accelerator that provides pre-seed investment and mentoring for various early stage startups.",
        "location_identifiers": "Boulder, Colorado, United States, North America",
        "website_url": "https://www.techstars.com",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/sfdhykaf0zcn2oavawe5",
        "api_identifier": "3718597a-dd39-6661-3630-09cdd43bcac2",
        "founded_year": "2006",
        "ai_prompt": "Techstars has emerged as a leading accelerator program, poised for significant growth in both the near and long term as the startup ecosystem flourishes. With a track record of mentoring and investing in over 2,500 startups globally, Techstars is strategically positioned to capitalize on the rising demand for early-stage funding and guidance. In the near term, as of October 2023, the company should continue to attract promising startups, expanding its portfolio further. In the long term, Techstars aims to solidify its reputation in the startup landscape by fostering innovation and scaling its operations. The primary product offerings include mentorship and pre-seed investments, catering mainly to tech-focused entrepreneurs. While the company remains private, a future IPO could see share prices ranging from $20 to $35 based on industry benchmarks, further positioning Techstars as a valuable player in the venture capital space.",
        "categories": "Technology",
        "num_employees_enum": "51-100",
        "revenue_range": "$10M - $50M",
        "investors": "Techstars, Foundry Group, Amplify Partners, BlueRun Ventures, Bullpen Capital, Collaboration Capital, Costanoa Ventures, Kauffman Foundation, Techstars Alumni.",
    },
    {
        "company_name": "Centrus Energy",
        "short_description": "Centrus Energy supplies low enriched uranium (LEU) for commercial nuclear power plants.",
        "location_identifiers": "Bethesda, Maryland, United States, North America",
        "website_url": "https://www.centrusenergy.com",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/rlx3fil13f24vglujdj5",
        "api_identifier": "c7b57cd2-84b8-4884-b8c4-2f5298effe19",
        "founded_year": "2007",
        "ai_prompt": "Centrus Energy is poised for significant growth in the nuclear energy sector, fueled by global investments in clean energy and initiatives to reduce carbon emissions. In the near term, the company is likely to benefit from increasing demand for low enriched uranium (LEU) as countries seek stable, carbon-free energy sources. Over the long term, Centrus may expand its market presence, particularly as nuclear power’s role in sustainable energy frameworks gains prominence. With a focus on supplying LEU to commercial nuclear power plants, Centrus can potentially attract a diverse clientele, ranging from energy producers to governmental agencies. As of recent evaluations, analysts expect Centrus's share price to range between $20 to $30, reflecting investor confidence in its strategic initiatives.",
        "categories": "Energy",
        "num_employees_enum": "101-500",
        "revenue_range": "$100M - $500M",
        "investors": "Centrus Energy has had various investors including the U.S. Government, private equity firms, and institutional investors, but specific names may vary over time.",
    },
    {
        "company_name": "SpaceX",
        "short_description": "SpaceX is an aviation and aerospace company that focuses on reducing the costs associated with space travel by using reusable rockets.",
        "location_identifiers": "Hawthorne, California, United States, North America",
        "website_url": "https://www.spacex.com",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/u196odmivjn2dvw09xhx",
        "api_identifier": "2372e88e-240a-a19c-c549-bd262c670ee1",
        "founded_year": "2002",
        "ai_prompt": "SpaceX has positioned itself as a leader in aerospace innovation with its reusable rocket technology, aiming to transform the cost structure of space travel. In the near term, as they expand satellite launches through the Starlink program, I expect substantial revenue growth, potentially reaching $30 billion by 2025. Long-term, SpaceX's ambitious goal of Mars colonization could revolutionize human space exploration. Their primary customers include NASA and commercial satellite companies, and analysts project that the share price could range from $250 to $350 in the coming years, reflecting their growing market influence.",
        "categories": "Aerospace & Defense",
        "num_employees_enum": "1001-5000",
        "revenue_range": "$1B - $5B",
        "investors": "Founders Fund, Draper Fisher Jurvetson, Google, Fidelity Investments, Luxembourg Government, Baidu, NASA, Alphabet Inc.",
    },
    {
        "company_name": "Element451",
        "short_description": "Element451 is an admissions marketing technology and CRM platform that brings students and colleges together.",
        "location_identifiers": "Raleigh, North Carolina, United States, North America",
        "website_url": "https://element451.com",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/vvixjdua9dd3ng9vtu7d",
        "api_identifier": "9d429742-919a-49b1-a443-b902cb59d485",
        "founded_year": "2015",
        "ai_prompt": "Element451 is poised for significant growth in both the near and long term as the demand for digital transformation in higher education continues to rise. With a focus on enhancing student engagement and streamlining admissions processes, the company is well-positioned to capitalize on the evolving landscape of educational technology. Their main product is an admissions marketing technology and CRM platform that connects colleges with prospective students effectively. Their primary customers include colleges and universities seeking innovative solutions for recruitment. Given the increasing investment in EdTech, Element451's projected share price could range between $20 to $30 as it expands its market presence and continues to innovate.",
        "categories": "Education",
        "num_employees_enum": "51-100",
        "revenue_range": "$1M - $5M",
        "investors": "University Ventures, CincyTech, Eon Business Investments, Wavemaker Partners",
    },
    {
        "company_name": "IonQ",
        "short_description": "IONQ develops general-purpose quantum information processors to solve the world’s complex problems.",
        "location_identifiers": "College Park, Maryland, United States, North America",
        "website_url": "https://ionq.com",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/ioz8adoqarm3dcoovo2w",
        "api_identifier": "9caa6135-6881-6ad6-9e0f-f112e87dd455",
        "founded_year": "2015",
        "ai_prompt": "IonQ is poised for significant growth in both the near and long term as the demand for quantum computing solutions escalates across various industries, from pharmaceuticals to finance. With partnerships with major companies like Microsoft and Google, IonQ is well-positioned to leverage its technology in solving intricate problems that traditional computers struggle with. In recent developments, the company reported a revenue increase of over 60% year-on-year. Their flagship product, the IonQ Quantum Computer, is targeted at research institutions and enterprises seeking cutting-edge computational power. Analysts anticipate that IonQ's stock may range between $15 and $25 in the next year as the market recognizes its potential.",
        "categories": "Technology",
        "num_employees_enum": "101-500",
        "revenue_range": "$10M - $50M",
        "investors": "Microsoft, D.E. Shaw Group, Goldman Sachs, Hyundai Motor Group, Mubadala Investment Company",
    },
    {
        "company_name": "Veeam Software",
        "short_description": "Veeam provides data resilience and data management solutions for cloud, virtual, and physical environments.",
        "location_identifiers": "Columbus, Ohio, United States, North America",
        "website_url": "http://www.veeam.com",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/5c1367ed00d5410fa0e308d556ec2645",
        "api_identifier": "8e4fc8f3-a74c-7cae-9fea-9d4333002165",
        "founded_year": "2006",
        "ai_prompt": "Veeam Software is well-positioned for robust near-term and long-term growth as demand for data management solutions continues to rise across cloud and hybrid environments. In the coming years, the emphasis on data resilience, especially with increasing cyber threats, is expected to drive market expansion. Veeam's primary offerings, such as its Backup & Replication suite, serve a diverse clientele, including large enterprises and SMBs. As of my last update, Veeam's valuation was around $5 billion with anticipated growth in share prices potentially reaching the $6-8 billion range as they expand their innovative solutions.",
        "categories": "Technology",
        "num_employees_enum": "1001-5000",
        "revenue_range": "$500M - $1B",
        "investors": "Insight Partners, Cisco Investments, Goldman Sachs, Zscaler, DFI Capital",
    },
    {
        "company_name": "Rigetti Computing",
        "short_description": "Rigetti Computing is a quantum computing company that builds and deploys full-stack quantum systems with superconducting qubits.",
        "location_identifiers": "Berkeley, California, United States, North America",
        "website_url": "http://www.rigetti.com",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/p4sjulxrb3mawum4kj3p",
        "api_identifier": "f398bfe7-5902-8dea-e148-4d9fd6d20a00",
        "founded_year": "2013",
        "ai_prompt": "Rigetti Computing, a leader in quantum computing, is poised for significant growth in both the near and long term as businesses increasingly seek advanced computational solutions. With a focus on superconducting qubits, their full-stack quantum systems are designed to tackle complex problems across various industries, including finance and pharmaceuticals. As the demand for quantum computing intensifies, Rigetti's innovative technologies could elevate its market position substantially. Currently, they have partnerships with notable entities and aim to broaden their customer base dramatically. Analysts expect Rigetti's share price to stabilize between $10 to $20, reflecting its potential as a key player in the emerging quantum landscape. Their flagship product, the quantum computing platform, remains crucial for developers and researchers pioneering quantum applications.",
        "categories": "Technology",
        "num_employees_enum": "101-500",
        "revenue_range": "$10M - $50M",
        "investors": "Rigetti Computing Investors: Andreessen Horowitz, Y Combinator, Franklin Templeton, 1Sharpe Ventures, Data Collective DCVC, The Venture Reality Fund, GGV Capital",
    },
    {
        "company_name": "AST SpaceMobile",
        "short_description": "AST SpaceMobile is a space-based broadband cellular network company for unmodified mobile devices.",
        "location_identifiers": "Midland, Texas, United States, North America",
        "website_url": "https://ast-science.com",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/ussry0g1gufmmq4h7fpw",
        "api_identifier": "68c1b996-c37f-4663-9a8d-5e180bac356f",
        "founded_year": "2017",
        "ai_prompt": "AST SpaceMobile is poised for significant growth as it aims to bridge connectivity gaps in underserved areas through its innovative space-based cellular network. In the near term, successful test launches could enhance its valuation and attract partnerships with major telecom providers. Long-term, the company envisions a global network capable of providing broadband services directly to unmodified mobile devices, potentially reaching billions of users. With a clear focus on enhancing mobile coverage in rural and remote regions, AST SpaceMobile's primary product is its satellite-enabled broadband service. Its key customers include mobile network operators looking to expand their service offerings. Analysts predict a share price range of $10 to $20 as the company garners market traction and expands its operations.",
        "categories": "Telecommunications",
        "num_employees_enum": "101-500",
        "revenue_range": "$10M - $50M",
        "investors": "Lone Star Fund, Vodafone Group, Rakuten, AT&T, Qualcomm, SiriusXM",
    },
    {
        "company_name": "StepStone Group",
        "short_description": "StepStone Group provides investors with customized portfolios that integrate primaries, secondaries, and co-investments.",
        "location_identifiers": "New York, New York, United States, North America",
        "website_url": "https://www.stepstoneglobal.com",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/1a0f97eb4f5b406099a2271e9cca4479",
        "api_identifier": "0d1a939e-b9bd-76ad-3264-51d4901d5cc0",
        "founded_year": "2007",
        "ai_prompt": "StepStone Group, as a leader in private markets solutions, is poised for robust near-term and long-term growth, driven by increasing institutional demand for customized portfolio strategies. With a focus on integrating primaries, secondaries, and co-investments, the firm is well-positioned to capitalize on the expanding alternative investment landscape. Currently managing over $500 billion in total assets, StepStone Group caters primarily to pension funds, endowments, and family offices. As the market evolves, they aim to enhance their innovative offerings and could see their share price range between $40 to $60, reflecting solid investor confidence in their bespoke investment strategies.",
        "categories": "Financial Services",
        "num_employees_enum": "501-1000",
        "revenue_range": "$500M - $1B",
        "investors": "StepStone Group, private equity firms, institutional investors, family offices, high-net-worth individuals, public pension funds, endowments, foundations.",
    },
    {
        "company_name": "Shift4 Payments",
        "short_description": "Shift4 Payments is a provider of secure payment processing solutions.",
        "location_identifiers": "Allentown, Pennsylvania, United States, North America",
        "website_url": "https://www.shift4.com/",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/l6xacanao1keyxmu9xqp",
        "api_identifier": "6f59edd2-9872-cf32-48aa-21ad63666997",
        "founded_year": "2005",
        "ai_prompt": "Shift4 Payments is poised for significant growth in both the near and long term, driven by the increasing demand for secure payment processing solutions across diverse industries. With a projected revenue increase of around 30% year-over-year, the company is capitalizing on the shift towards digital payments and e-commerce expansion. Its main products, including advanced payment gateways and integrated POS systems, cater to a range of customers from hospitality to retail. With an anticipated growth trajectory, analysts estimate Shift4’s share price could range between $40 to $60 in the forthcoming quarters, reflecting investor confidence in its innovative offerings and market reach.",
        "categories": "Finance",
        "num_employees_enum": "1001-5000",
        "revenue_range": "$1B - $5B",
        "investors": "Shift4 Capital, Adage Capital Management, The Vanguard Group, BlackRock, Fidelity Investments",
    },
    {
        "company_name": "Public",
        "short_description": "Public is a fractional investing platform that allows members to build diverse portfolios, including stocks, ETFs, crypto, and NFTs.",
        "location_identifiers": "New York, New York, United States, North America",
        "website_url": "https://public.com",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/httrwjcuxry97mcvwei8",
        "api_identifier": "82eeb304-dc55-01e9-57c1-fa4eb40a10e2",
        "founded_year": "2019",
        "ai_prompt": "Public is poised for significant growth in both the near and long term, capitalizing on the increasing interest in fractional investing and diversification among retail investors. As of October 2023, the platform has gained traction with over 1 million active users who appreciate its user-friendly interface and community features, highlighting the shift toward digital investment solutions. In the coming years, Public may expand its offerings and integrate more educational resources, positioning itself as a leading player in the market. The main product includes a diverse portfolio system that encompasses stocks, ETFs, crypto, and NFTs, targeting millennial and Gen Z investors. Analysts anticipate that with its growing user base and market innovations, Public's share price could range between $20 to $30, reflecting a burgeoning demand for accessible investment platforms.",
        "categories": "Finance",
        "num_employees_enum": "51-100",
        "revenue_range": "$10M - $50M",
        "investors": "Accredited Investors, Social Capital, Galactic Ventures, Coatue Management, Initialized Capital, Acrew Capital, and other angel investors.",
    },
    {
        "company_name": "NVIDIA",
        "short_description": "NVIDIA is a computing platform company operating at the intersection of graphics, HPC, and AI.",
        "location_identifiers": "Santa Clara, California, United States, North America",
        "website_url": "https://www.nvidia.com",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/v1502744943/jhowtgkdwv2aa1eodg2b.png",
        "api_identifier": "ee17319e-f5ee-9c9a-6500-edf82b4fbf05",
        "founded_year": "1993",
        "ai_prompt": "NVIDIA is poised for robust growth in both the near and long term, driven by its leadership in graphics processing units (GPUs) and artificial intelligence (AI) technologies. As businesses increasingly adopt AI for optimization and automation, NVIDIA's GPUs have become essential for tasks ranging from data analysis to gaming graphics. In 2023, the company reported a revenue of $26.91 billion, reflecting a 61% increase year-over-year. Its main products include the GeForce and Quadro series, targeting gamers and professionals, while its data center offerings cater to cloud service providers and enterprises. Analysts predict a share price range of $450 to $500 over the next year, fueled by ongoing innovation and expanding market demand.",
        "categories": "Technology",
        "num_employees_enum": "10001-50000",
        "revenue_range": "$10B - $50B",
        "investors": "The Vanguard Group, BlackRock, T. Rowe Price, Fidelity Investments, State Street Corporation, Invesco, Northern Trust, Capital Group, Wells Fargo, Morgan Stanley",
    },
    {
        "company_name": "Hulu",
        "short_description": "Hulu is an online video service that offers a selection of hit shows, clips, movies, and documentaries through its website. ",
        "location_identifiers": "Los Angeles, California, United States, North America",
        "website_url": "https://www.hulu.com",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/bk8cux6dapq8qjzylfaj",
        "api_identifier": "e4f41fbf-eea3-2db9-0c69-cd16f5cfc0e9",
        "founded_year": "2008",
        "ai_prompt": "Hulu, as a leading online video streaming service, is positioned for continued growth in both the near and long term. With an expanding library of hit shows, movies, and documentaries, Hulu attracts a diverse audience, including millennials and Gen Z, who prefer on-demand content. Its recent investments in original programming could drive subscriber growth and engagement. In 2023, Hulu boasted over 48 million subscribers, with expectations of reaching 60 million in the next few years. The company competes in a crowded market, yet its unique combination of live TV and on-demand content appeals to various viewer preferences. Investors may anticipate a share price range between $60 and $80 as Hulu solidifies its market position while catering to its primary customers—streaming enthusiasts seeking quality entertainment.",
        "categories": "Media & Entertainment",
        "num_employees_enum": "1001-5000",
        "revenue_range": "$1B - $5B",
        "investors": "The Walt Disney Company, Comcast, AT&T, Warner Bros. Discovery",
    },
    {
        "company_name": "Capitolis",
        "short_description": "Capitolis provides technology solutions for optimizing capital markets and investments.",
        "location_identifiers": "New York, New York, United States, North America",
        "website_url": "https://www.capitolis.com",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/lokbciw7oxvdsqouxtcq",
        "api_identifier": "86131925-3871-4911-98b7-3e81053be9f5",
        "founded_year": "2017",
        "ai_prompt": "Capitolis is well-positioned to capture growth in the capital markets sector, especially as financial institutions increasingly seek innovative technology solutions to optimize operations and enhance efficiencies. In the near term, we can expect Capitolis to expand its offerings, driven by the growing demand for robust data analytics and risk management tools. Over the long haul, its focus on collaboration and seamless integration with banks and financial firms will likely cement its industry leadership. Notable customers include major financial entities, and their flagship product enhances capital optimization strategies. While current market sentiments are broad, analysts suggest a share price range of approximately $20 to $30, reflecting Capitolis' potential for sustained growth and profitability.",
        "categories": "Finance",
        "num_employees_enum": "51-100",
        "revenue_range": "$10M - $50M",
        "investors": "JP Morgan, Citi, Wells Fargo, Goldman Sachs, BlackRock, HSBC, Ares Management, Allen & Company",
    },
    {
        "company_name": "Together AI",
        "short_description": "Together AI is a cloud-based platform designed for constructing open-source generative AI and infrastructure for developing AI models.",
        "location_identifiers": "San Francisco, California, United States, North America",
        "website_url": "https://www.together.ai",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/pgexmaaspfjz1xaqfluc",
        "api_identifier": "82aee40b-3dcb-4678-adc4-73b8e1c91a7e",
        "founded_year": "2023",
        "ai_prompt": "Together AI stands at the forefront of the generative AI revolution, with a promising trajectory in both short and long-term business development. Given the accelerating demand for cloud-based AI solutions, I anticipate their robust growth especially as enterprises swiftly adopt AI-driven tools. Their open-source platform empowers developers, resulting in a diverse customer base that includes tech startups, research institutions, and enterprises seeking to innovate. As they refine their infrastructure and expand offerings, market analysts project a share price range of $15-$25, reflecting investor confidence in their transformative potential. The company's core product—an accessible platform for building generative AI models—positions them strategically in a competitive landscape.",
        "categories": "Technology",
        "num_employees_enum": "51-100",
        "revenue_range": "$5M - $10M",
        "investors": "As of my last update in October 2023, the specific investors for Together AI are not publicly available. Please consult the latest financial news or company press releases for the most accurate information.",
    },
    {
        "company_name": "Poseida Therapeutics",
        "short_description": "Poseida Therapeutics is a biopharmaceutical company utilizing gene engineering capabilities to develop targeted therapeutics.",
        "location_identifiers": "San Diego, California, United States, North America",
        "website_url": "http://poseida.com",
        "logo_url": "https://images.crunchbase.com/image/upload/t_cb-default-original/f4ibl0cus5idnv5q7by8",
        "api_identifier": "0e457bab-6ece-077d-445f-93d757fd68d2",
        "founded_year": "2014",
        "ai_prompt": "Poseida Therapeutics, focused on innovative gene engineering to create targeted therapies, is poised for significant growth in both the near and long term. The company's unique Pseudointronic Technology is designed to optimize gene delivery, enhancing therapeutic efficacy for various cancers and rare diseases. With a strong pipeline that includes P-BCMA-101 for multiple myeloma, Poseida aims to attract partnerships and bolster its position in the competitive biopharmaceutical market. Analysts project a share price range between $10 to $20, reflecting optimistic expectations based on their product advancements and potential customer base in the oncology sector.",
        "categories": "Biotechnology",
        "num_employees_enum": "101-500",
        "revenue_range": "$10M - $50M",
        "investors": "Atlas Venture, Aisling Capital, OrbiMed Advisors, Fidelity Management & Research Company, Perceptive Advisors, The Bank of New York Mellon, Novartis Venture Fund",
    },
]
