instruments = [
    {
        "company_id": 1,
        "instrument_name": "OpenAI Common Share",
        "issuer_user_id": 2,
        "issued_on_et": "2015-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 3152246.24,
        "updated_issued_quantity": 16172,
        "updated_price": 194.92,
    },
    {
        "company_id": 1,
        "instrument_name": "OpenAI Preferred Share",
        "issuer_user_id": 2,
        "issued_on_et": "2015-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 1182092.34,
        "updated_issued_quantity": 4043,
        "updated_price": 292.38,
    },
    {
        "company_id": 1,
        "instrument_name": "OpenAI Executive Share",
        "issuer_user_id": 2,
        "issued_on_et": "2015-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 443284.63,
        "updated_issued_quantity": 1010,
        "updated_price": 438.57,
    },
    {
        "company_id": 2,
        "instrument_name": "Anthropic Common Share",
        "issuer_user_id": 3,
        "issued_on_et": "2020-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 9049470.18,
        "updated_issued_quantity": 92238,
        "updated_price": 98.11,
    },
    {
        "company_id": 2,
        "instrument_name": "Anthropic Preferred Share",
        "issuer_user_id": 3,
        "issued_on_et": "2020-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 3393551.32,
        "updated_issued_quantity": 23059,
        "updated_price": 147.16,
    },
    {
        "company_id": 2,
        "instrument_name": "Anthropic Executive Share",
        "issuer_user_id": 3,
        "issued_on_et": "2020-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 1272581.74,
        "updated_issued_quantity": 5764,
        "updated_price": 220.75,
    },
    {
        "company_id": 3,
        "instrument_name": "xAI Common Share",
        "issuer_user_id": 4,
        "issued_on_et": "2023-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 2395046.32,
        "updated_issued_quantity": 13592,
        "updated_price": 176.21,
    },
    {
        "company_id": 3,
        "instrument_name": "xAI Preferred Share",
        "issuer_user_id": 4,
        "issued_on_et": "2023-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 898142.37,
        "updated_issued_quantity": 3398,
        "updated_price": 264.31,
    },
    {
        "company_id": 3,
        "instrument_name": "xAI Executive Share",
        "issuer_user_id": 4,
        "issued_on_et": "2023-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 336803.39,
        "updated_issued_quantity": 849,
        "updated_price": 396.47,
    },
    {
        "company_id": 4,
        "instrument_name": "Perplexity Common Share",
        "issuer_user_id": 5,
        "issued_on_et": "2022-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 8760076.4,
        "updated_issued_quantity": 94540,
        "updated_price": 92.66,
    },
    {
        "company_id": 4,
        "instrument_name": "Perplexity Preferred Share",
        "issuer_user_id": 5,
        "issued_on_et": "2022-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 3285028.65,
        "updated_issued_quantity": 23635,
        "updated_price": 138.99,
    },
    {
        "company_id": 4,
        "instrument_name": "Perplexity Executive Share",
        "issuer_user_id": 5,
        "issued_on_et": "2022-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 1231885.74,
        "updated_issued_quantity": 5908,
        "updated_price": 208.49,
    },
    {
        "company_id": 5,
        "instrument_name": "TPG Common Share",
        "issuer_user_id": 6,
        "issued_on_et": "1992-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 18809437.12,
        "updated_issued_quantity": 97096,
        "updated_price": 193.72,
    },
    {
        "company_id": 5,
        "instrument_name": "TPG Preferred Share",
        "issuer_user_id": 6,
        "issued_on_et": "1992-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 7053538.92,
        "updated_issued_quantity": 24274,
        "updated_price": 290.58,
    },
    {
        "company_id": 5,
        "instrument_name": "TPG Executive Share",
        "issuer_user_id": 6,
        "issued_on_et": "1992-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 2645077.1,
        "updated_issued_quantity": 6068,
        "updated_price": 435.87,
    },
    {
        "company_id": 6,
        "instrument_name": "Bluesky Common Share",
        "issuer_user_id": 7,
        "issued_on_et": "2022-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 2852726.34,
        "updated_issued_quantity": 26167,
        "updated_price": 109.02,
    },
    {
        "company_id": 6,
        "instrument_name": "Bluesky Preferred Share",
        "issuer_user_id": 7,
        "issued_on_et": "2022-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 1069772.38,
        "updated_issued_quantity": 6541,
        "updated_price": 163.53,
    },
    {
        "company_id": 6,
        "instrument_name": "Bluesky Executive Share",
        "issuer_user_id": 7,
        "issued_on_et": "2022-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 401164.64,
        "updated_issued_quantity": 1635,
        "updated_price": 245.3,
    },
    {
        "company_id": 7,
        "instrument_name": "Polymarket Common Share",
        "issuer_user_id": 8,
        "issued_on_et": "2018-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 5428442.55,
        "updated_issued_quantity": 49507,
        "updated_price": 109.65,
    },
    {
        "company_id": 7,
        "instrument_name": "Polymarket Preferred Share",
        "issuer_user_id": 8,
        "issued_on_et": "2018-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 2035665.96,
        "updated_issued_quantity": 12376,
        "updated_price": 164.48,
    },
    {
        "company_id": 7,
        "instrument_name": "Polymarket Executive Share",
        "issuer_user_id": 8,
        "issued_on_et": "2018-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 763374.73,
        "updated_issued_quantity": 3094,
        "updated_price": 246.71,
    },
    {
        "company_id": 8,
        "instrument_name": "Cyera Common Share",
        "issuer_user_id": 9,
        "issued_on_et": "2021-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 6146760.84,
        "updated_issued_quantity": 42603,
        "updated_price": 144.28,
    },
    {
        "company_id": 8,
        "instrument_name": "Cyera Preferred Share",
        "issuer_user_id": 9,
        "issued_on_et": "2021-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 2305035.31,
        "updated_issued_quantity": 10650,
        "updated_price": 216.42,
    },
    {
        "company_id": 8,
        "instrument_name": "Cyera Executive Share",
        "issuer_user_id": 9,
        "issued_on_et": "2021-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 864388.24,
        "updated_issued_quantity": 2662,
        "updated_price": 324.63,
    },
    {
        "company_id": 9,
        "instrument_name": "Neuralink Common Share",
        "issuer_user_id": 10,
        "issued_on_et": "2016-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 8508187.6,
        "updated_issued_quantity": 76430,
        "updated_price": 111.32,
    },
    {
        "company_id": 9,
        "instrument_name": "Neuralink Preferred Share",
        "issuer_user_id": 10,
        "issued_on_et": "2016-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 3190570.35,
        "updated_issued_quantity": 19107,
        "updated_price": 166.98,
    },
    {
        "company_id": 9,
        "instrument_name": "Neuralink Executive Share",
        "issuer_user_id": 10,
        "issued_on_et": "2016-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 1196463.88,
        "updated_issued_quantity": 4776,
        "updated_price": 250.47,
    },
    {
        "company_id": 10,
        "instrument_name": "BlackRock Common Share",
        "issuer_user_id": 11,
        "issued_on_et": "1988-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 141176.25,
        "updated_issued_quantity": 3525,
        "updated_price": 40.05,
    },
    {
        "company_id": 10,
        "instrument_name": "BlackRock Preferred Share",
        "issuer_user_id": 11,
        "issued_on_et": "1988-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 52941.09,
        "updated_issued_quantity": 881,
        "updated_price": 60.07,
    },
    {
        "company_id": 10,
        "instrument_name": "BlackRock Executive Share",
        "issuer_user_id": 11,
        "issued_on_et": "1988-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 19852.91,
        "updated_issued_quantity": 220,
        "updated_price": 90.11,
    },
    {
        "company_id": 11,
        "instrument_name": "Rocket Lab Common Share",
        "issuer_user_id": 12,
        "issued_on_et": "2006-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 5268889.98,
        "updated_issued_quantity": 96819,
        "updated_price": 54.42,
    },
    {
        "company_id": 11,
        "instrument_name": "Rocket Lab Preferred Share",
        "issuer_user_id": 12,
        "issued_on_et": "2006-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 1975833.74,
        "updated_issued_quantity": 24204,
        "updated_price": 81.63,
    },
    {
        "company_id": 11,
        "instrument_name": "Rocket Lab Executive Share",
        "issuer_user_id": 12,
        "issued_on_et": "2006-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 740937.65,
        "updated_issued_quantity": 6051,
        "updated_price": 122.44,
    },
    {
        "company_id": 12,
        "instrument_name": "SoundHound Common Share",
        "issuer_user_id": 13,
        "issued_on_et": "2005-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 5806478.88,
        "updated_issued_quantity": 65256,
        "updated_price": 88.98,
    },
    {
        "company_id": 12,
        "instrument_name": "SoundHound Preferred Share",
        "issuer_user_id": 13,
        "issued_on_et": "2005-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 2177429.58,
        "updated_issued_quantity": 16314,
        "updated_price": 133.47,
    },
    {
        "company_id": 12,
        "instrument_name": "SoundHound Executive Share",
        "issuer_user_id": 13,
        "issued_on_et": "2005-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 816536.09,
        "updated_issued_quantity": 4078,
        "updated_price": 200.2,
    },
    {
        "company_id": 13,
        "instrument_name": "LambdaTest Common Share",
        "issuer_user_id": 14,
        "issued_on_et": "2017-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 1385211.0,
        "updated_issued_quantity": 32028,
        "updated_price": 43.25,
    },
    {
        "company_id": 13,
        "instrument_name": "LambdaTest Preferred Share",
        "issuer_user_id": 14,
        "issued_on_et": "2017-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 519454.12,
        "updated_issued_quantity": 8007,
        "updated_price": 64.88,
    },
    {
        "company_id": 13,
        "instrument_name": "LambdaTest Executive Share",
        "issuer_user_id": 14,
        "issued_on_et": "2017-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 194795.3,
        "updated_issued_quantity": 2001,
        "updated_price": 97.31,
    },
    {
        "company_id": 14,
        "instrument_name": "International Finance Corporation Common Share",
        "issuer_user_id": 15,
        "issued_on_et": "1956-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 4981524.24,
        "updated_issued_quantity": 34936,
        "updated_price": 142.59,
    },
    {
        "company_id": 14,
        "instrument_name": "International Finance Corporation Preferred Share",
        "issuer_user_id": 15,
        "issued_on_et": "1956-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 1868071.59,
        "updated_issued_quantity": 8734,
        "updated_price": 213.88,
    },
    {
        "company_id": 14,
        "instrument_name": "International Finance Corporation Executive Share",
        "issuer_user_id": 15,
        "issued_on_et": "1956-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 700526.85,
        "updated_issued_quantity": 2183,
        "updated_price": 320.83,
    },
    {
        "company_id": 15,
        "instrument_name": "Techstars Common Share",
        "issuer_user_id": 16,
        "issued_on_et": "2006-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 421301.44,
        "updated_issued_quantity": 3647,
        "updated_price": 115.52,
    },
    {
        "company_id": 15,
        "instrument_name": "Techstars Preferred Share",
        "issuer_user_id": 16,
        "issued_on_et": "2006-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 157988.04,
        "updated_issued_quantity": 911,
        "updated_price": 173.28,
    },
    {
        "company_id": 15,
        "instrument_name": "Techstars Executive Share",
        "issuer_user_id": 16,
        "issued_on_et": "2006-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 59245.52,
        "updated_issued_quantity": 227,
        "updated_price": 259.92,
    },
    {
        "company_id": 16,
        "instrument_name": "Centrus Energy Common Share",
        "issuer_user_id": 17,
        "issued_on_et": "2007-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 13902894.9,
        "updated_issued_quantity": 81518,
        "updated_price": 170.55,
    },
    {
        "company_id": 16,
        "instrument_name": "Centrus Energy Preferred Share",
        "issuer_user_id": 17,
        "issued_on_et": "2007-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 5213585.59,
        "updated_issued_quantity": 20379,
        "updated_price": 255.83,
    },
    {
        "company_id": 16,
        "instrument_name": "Centrus Energy Executive Share",
        "issuer_user_id": 17,
        "issued_on_et": "2007-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 1955094.6,
        "updated_issued_quantity": 5094,
        "updated_price": 383.74,
    },
    {
        "company_id": 17,
        "instrument_name": "SpaceX Common Share",
        "issuer_user_id": 18,
        "issued_on_et": "2002-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 18358893.72,
        "updated_issued_quantity": 98418,
        "updated_price": 186.54,
    },
    {
        "company_id": 17,
        "instrument_name": "SpaceX Preferred Share",
        "issuer_user_id": 18,
        "issued_on_et": "2002-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 6884585.15,
        "updated_issued_quantity": 24604,
        "updated_price": 279.81,
    },
    {
        "company_id": 17,
        "instrument_name": "SpaceX Executive Share",
        "issuer_user_id": 18,
        "issued_on_et": "2002-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 2581719.43,
        "updated_issued_quantity": 6151,
        "updated_price": 419.72,
    },
    {
        "company_id": 18,
        "instrument_name": "Element451 Common Share",
        "issuer_user_id": 19,
        "issued_on_et": "2015-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 7839819.77,
        "updated_issued_quantity": 42871,
        "updated_price": 182.87,
    },
    {
        "company_id": 18,
        "instrument_name": "Element451 Preferred Share",
        "issuer_user_id": 19,
        "issued_on_et": "2015-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 2939932.41,
        "updated_issued_quantity": 10717,
        "updated_price": 274.31,
    },
    {
        "company_id": 18,
        "instrument_name": "Element451 Executive Share",
        "issuer_user_id": 19,
        "issued_on_et": "2015-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 1102474.66,
        "updated_issued_quantity": 2679,
        "updated_price": 411.46,
    },
    {
        "company_id": 19,
        "instrument_name": "IonQ Common Share",
        "issuer_user_id": 20,
        "issued_on_et": "2015-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 1717192.25,
        "updated_issued_quantity": 50137,
        "updated_price": 34.25,
    },
    {
        "company_id": 19,
        "instrument_name": "IonQ Preferred Share",
        "issuer_user_id": 20,
        "issued_on_et": "2015-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 643947.09,
        "updated_issued_quantity": 12534,
        "updated_price": 51.38,
    },
    {
        "company_id": 19,
        "instrument_name": "IonQ Executive Share",
        "issuer_user_id": 20,
        "issued_on_et": "2015-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 241480.16,
        "updated_issued_quantity": 3133,
        "updated_price": 77.06,
    },
    {
        "company_id": 20,
        "instrument_name": "Veeam Software Common Share",
        "issuer_user_id": 21,
        "issued_on_et": "2006-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 6107186.01,
        "updated_issued_quantity": 65577,
        "updated_price": 93.13,
    },
    {
        "company_id": 20,
        "instrument_name": "Veeam Software Preferred Share",
        "issuer_user_id": 21,
        "issued_on_et": "2006-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 2290194.75,
        "updated_issued_quantity": 16394,
        "updated_price": 139.69,
    },
    {
        "company_id": 20,
        "instrument_name": "Veeam Software Executive Share",
        "issuer_user_id": 21,
        "issued_on_et": "2006-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 858823.03,
        "updated_issued_quantity": 4098,
        "updated_price": 209.54,
    },
    {
        "company_id": 21,
        "instrument_name": "Rigetti Computing Common Share",
        "issuer_user_id": 22,
        "issued_on_et": "2013-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 6390144.27,
        "updated_issued_quantity": 60507,
        "updated_price": 105.61,
    },
    {
        "company_id": 21,
        "instrument_name": "Rigetti Computing Preferred Share",
        "issuer_user_id": 22,
        "issued_on_et": "2013-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 2396304.1,
        "updated_issued_quantity": 15126,
        "updated_price": 158.41,
    },
    {
        "company_id": 21,
        "instrument_name": "Rigetti Computing Executive Share",
        "issuer_user_id": 22,
        "issued_on_et": "2013-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 898614.04,
        "updated_issued_quantity": 3781,
        "updated_price": 237.62,
    },
    {
        "company_id": 22,
        "instrument_name": "AST SpaceMobile Common Share",
        "issuer_user_id": 23,
        "issued_on_et": "2017-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 10170615.42,
        "updated_issued_quantity": 54911,
        "updated_price": 185.22,
    },
    {
        "company_id": 22,
        "instrument_name": "AST SpaceMobile Preferred Share",
        "issuer_user_id": 23,
        "issued_on_et": "2017-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 3813980.78,
        "updated_issued_quantity": 13727,
        "updated_price": 277.83,
    },
    {
        "company_id": 22,
        "instrument_name": "AST SpaceMobile Executive Share",
        "issuer_user_id": 23,
        "issued_on_et": "2017-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 1430242.79,
        "updated_issued_quantity": 3431,
        "updated_price": 416.75,
    },
    {
        "company_id": 23,
        "instrument_name": "StepStone Group Common Share",
        "issuer_user_id": 24,
        "issued_on_et": "2007-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 5804967.5,
        "updated_issued_quantity": 47750,
        "updated_price": 121.57,
    },
    {
        "company_id": 23,
        "instrument_name": "StepStone Group Preferred Share",
        "issuer_user_id": 24,
        "issued_on_et": "2007-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 2176862.81,
        "updated_issued_quantity": 11937,
        "updated_price": 182.35,
    },
    {
        "company_id": 23,
        "instrument_name": "StepStone Group Executive Share",
        "issuer_user_id": 24,
        "issued_on_et": "2007-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 816323.55,
        "updated_issued_quantity": 2984,
        "updated_price": 273.53,
    },
    {
        "company_id": 24,
        "instrument_name": "Shift4 Payments Common Share",
        "issuer_user_id": 25,
        "issued_on_et": "2005-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 11502922.5,
        "updated_issued_quantity": 68625,
        "updated_price": 167.62,
    },
    {
        "company_id": 24,
        "instrument_name": "Shift4 Payments Preferred Share",
        "issuer_user_id": 25,
        "issued_on_et": "2005-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 4313595.94,
        "updated_issued_quantity": 17156,
        "updated_price": 251.43,
    },
    {
        "company_id": 24,
        "instrument_name": "Shift4 Payments Executive Share",
        "issuer_user_id": 25,
        "issued_on_et": "2005-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 1617598.48,
        "updated_issued_quantity": 4289,
        "updated_price": 377.14,
    },
    {
        "company_id": 25,
        "instrument_name": "Public Common Share",
        "issuer_user_id": 26,
        "issued_on_et": "2019-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 10009359.36,
        "updated_issued_quantity": 87296,
        "updated_price": 114.66,
    },
    {
        "company_id": 25,
        "instrument_name": "Public Preferred Share",
        "issuer_user_id": 26,
        "issued_on_et": "2019-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 3753509.76,
        "updated_issued_quantity": 21824,
        "updated_price": 171.99,
    },
    {
        "company_id": 25,
        "instrument_name": "Public Executive Share",
        "issuer_user_id": 26,
        "issued_on_et": "2019-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 1407566.16,
        "updated_issued_quantity": 5456,
        "updated_price": 257.99,
    },
    {
        "company_id": 26,
        "instrument_name": "NVIDIA Common Share",
        "issuer_user_id": 27,
        "issued_on_et": "1993-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 67205.5,
        "updated_issued_quantity": 2570,
        "updated_price": 26.15,
    },
    {
        "company_id": 26,
        "instrument_name": "NVIDIA Preferred Share",
        "issuer_user_id": 27,
        "issued_on_et": "1993-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 25202.06,
        "updated_issued_quantity": 642,
        "updated_price": 39.22,
    },
    {
        "company_id": 26,
        "instrument_name": "NVIDIA Executive Share",
        "issuer_user_id": 27,
        "issued_on_et": "1993-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 9450.77,
        "updated_issued_quantity": 160,
        "updated_price": 58.84,
    },
    {
        "company_id": 27,
        "instrument_name": "Hulu Common Share",
        "issuer_user_id": 28,
        "issued_on_et": "2008-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 2502914.4,
        "updated_issued_quantity": 78708,
        "updated_price": 31.8,
    },
    {
        "company_id": 27,
        "instrument_name": "Hulu Preferred Share",
        "issuer_user_id": 28,
        "issued_on_et": "2008-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 938592.9,
        "updated_issued_quantity": 19677,
        "updated_price": 47.7,
    },
    {
        "company_id": 27,
        "instrument_name": "Hulu Executive Share",
        "issuer_user_id": 28,
        "issued_on_et": "2008-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 351972.34,
        "updated_issued_quantity": 4919,
        "updated_price": 71.55,
    },
    {
        "company_id": 28,
        "instrument_name": "Capitolis Common Share",
        "issuer_user_id": 29,
        "issued_on_et": "2017-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 1520246.3,
        "updated_issued_quantity": 11995,
        "updated_price": 126.74,
    },
    {
        "company_id": 28,
        "instrument_name": "Capitolis Preferred Share",
        "issuer_user_id": 29,
        "issued_on_et": "2017-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 570092.36,
        "updated_issued_quantity": 2998,
        "updated_price": 190.11,
    },
    {
        "company_id": 28,
        "instrument_name": "Capitolis Executive Share",
        "issuer_user_id": 29,
        "issued_on_et": "2017-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 213784.64,
        "updated_issued_quantity": 749,
        "updated_price": 285.16,
    },
    {
        "company_id": 29,
        "instrument_name": "Together AI Common Share",
        "issuer_user_id": 30,
        "issued_on_et": "2023-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 9183030.78,
        "updated_issued_quantity": 47514,
        "updated_price": 193.27,
    },
    {
        "company_id": 29,
        "instrument_name": "Together AI Preferred Share",
        "issuer_user_id": 30,
        "issued_on_et": "2023-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 3443636.54,
        "updated_issued_quantity": 11878,
        "updated_price": 289.91,
    },
    {
        "company_id": 29,
        "instrument_name": "Together AI Executive Share",
        "issuer_user_id": 30,
        "issued_on_et": "2023-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 1291363.7,
        "updated_issued_quantity": 2969,
        "updated_price": 434.86,
    },
    {
        "company_id": 30,
        "instrument_name": "Poseida Therapeutics Common Share",
        "issuer_user_id": 31,
        "issued_on_et": "2014-06-01",
        "instrument_type": "Common Share",
        "instrument_class": "Class A",
        "updated_value": 8229751.68,
        "updated_issued_quantity": 72624,
        "updated_price": 113.32,
    },
    {
        "company_id": 30,
        "instrument_name": "Poseida Therapeutics Preferred Share",
        "issuer_user_id": 31,
        "issued_on_et": "2014-06-01",
        "instrument_type": "Preferred Share",
        "instrument_class": "Class B",
        "updated_value": 3086156.88,
        "updated_issued_quantity": 18156,
        "updated_price": 169.98,
    },
    {
        "company_id": 30,
        "instrument_name": "Poseida Therapeutics Executive Share",
        "issuer_user_id": 31,
        "issued_on_et": "2014-06-01",
        "instrument_type": "Executive Share",
        "instrument_class": "Class C",
        "updated_value": 1157308.83,
        "updated_issued_quantity": 4539,
        "updated_price": 254.97,
    },
]
