"""empty message

Revision ID: 43904da0c06c
Revises: 
Create Date: 2024-11-21 16:14:00.395709

"""
from alembic import op
import sqlalchemy as sa
import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '43904da0c06c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('user_cash_balance', sa.Float(precision=2), nullable=True),
    sa.Column('amount_to_be_debited', sa.Float(precision=2), nullable=True),
    sa.Column('amount_to_be_credited', sa.Float(precision=2), nullable=True),
    sa.Column('user_available_balance', sa.Float(precision=2), nullable=True),
    sa.Column('is_issuer', sa.Boolean(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_on_et', sa.Date(), nullable=True),
    sa.Column('created_at_et', sa.DateTime(), nullable=True),
    sa.Column('updated_at_et', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('first_name'),
    sa.UniqueConstraint('last_name')
    )
    # ### end Alembic commands ###
    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
