"""empty message

Revision ID: 251c0856a47c
Revises: cf8e63a607cc
Create Date: 2024-11-24 14:47:26.449936

"""
from alembic import op
import sqlalchemy as sa
import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '251c0856a47c'
down_revision = 'cf8e63a607cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('offer_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('offered_price', sa.Float(precision=2), nullable=False),
    sa.Column('initial_quantity', sa.Integer(), nullable=False),
    sa.Column('remaining_quantity', sa.Integer(), nullable=True),
    sa.Column('offered_on_et', sa.DateTime(), nullable=True),
    sa.Column('settled_on_et', sa.Date(), nullable=True),
    sa.Column('created_at_et', sa.DateTime(), nullable=True),
    sa.Column('updated_at_et', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['offer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # add this within the upgrade function, at the very end
    if environment == "production":
        op.execute(f"ALTER TABLE offers SET SCHEMA {SCHEMA};")



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offers')
    # ### end Alembic commands ###
