"""empty message

Revision ID: d0eaf8278484
Revises: 251c0856a47c
Create Date: 2024-11-24 15:12:36.804943

"""
from alembic import op
import sqlalchemy as sa
import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")



# revision identifiers, used by Alembic.
revision = 'd0eaf8278484'
down_revision = '251c0856a47c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('listing_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('listed_price', sa.Float(precision=2), nullable=False),
    sa.Column('initial_quantity', sa.Integer(), nullable=False),
    sa.Column('remaining_quantity', sa.Integer(), nullable=True),
    sa.Column('listed_on_et', sa.DateTime(), nullable=True),
    sa.Column('settled_on_et', sa.Date(), nullable=True),
    sa.Column('created_at_et', sa.DateTime(), nullable=True),
    sa.Column('updated_at_et', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['listing_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    if environment == "production":
            op.execute(f"ALTER TABLE listings SET SCHEMA {SCHEMA};")



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listings')
    # ### end Alembic commands ###
