"""empty message

Revision ID: e03ca12aa2a3
Revises: 
Create Date: 2024-11-22 22:15:25.272347

"""
from alembic import op
import sqlalchemy as sa
import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'e03ca12aa2a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('short_description', sa.String(), nullable=True),
    sa.Column('ai_prompt', sa.String(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('location_identifiers', sa.String(), nullable=True),
    sa.Column('categories', sa.String(), nullable=True),
    sa.Column('num_employees_enum', sa.Integer(), nullable=True),
    sa.Column('revenue_range', sa.String(), nullable=True),
    sa.Column('operating_status', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('created_at_et', sa.DateTime(), nullable=True),
    sa.Column('updated_at_et', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('user_cash_balance', sa.Float(precision=2), nullable=True),
    sa.Column('amount_to_be_debited', sa.Float(precision=2), nullable=True),
    sa.Column('amount_to_be_credited', sa.Float(precision=2), nullable=True),
    sa.Column('user_available_balance', sa.Float(precision=2), nullable=True),
    sa.Column('is_issuer', sa.Boolean(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_on_et', sa.Date(), nullable=True),
    sa.Column('created_at_et', sa.DateTime(), nullable=True),
    sa.Column('updated_at_et', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE companies SET SCHEMA {SCHEMA};")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('companies')
    # ### end Alembic commands ###
